story_4/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('projects', views.projects, name='projects'),
    path('stories', views.stories, name='stories'),
    path('gallery', views.gallery, name='gallery'),
]

story_5/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add', views.add, name='add_course'),
    path('delete', views.delete, name='delete_course'),
]

story_ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='story_1/profil.html'))
    path('', include('story_4.urls')),
    path('courses/', include('story_5.urls')),
    path('events/', include('story_6.urls')),
    path('search/', include('story_8.urls')),
    path('accounts/', include('story_9.urls')),
]

story_5/models.py
from django.db import models

class Course(models.Model):
    course_name = models.CharField(max_length=200)
    lecturer = models.CharField(max_length=200)
    credits = models.IntegerField()
    description = models.CharField(max_length=200)

story_5/forms.py
from django import forms
from .models import Course

class AddForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'lecturer', 'credits', 'description']
    
    attrs = {'autocomplete':'off'}
    course_name = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs=attrs))
    lecturer = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs=attrs))
    credits = forms.IntegerField(required = True, widget=forms.NumberInput(attrs=attrs))
    description = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs=attrs))

story_5/views.py
from django.shortcuts import render
from .models import Course
from .forms import AddForm

def add(request):
    response = {'form' : AddForm}
    if (request.method == 'POST'):
        form = AddForm(request.POST or None)
        if (form.is_valid()):
            form.save()
            response['status'] = 'Course added successfully'
    return render(request, 'story_5/add.html', response)

def delete(request):
    response = {}
    if (request.method == 'POST'):
        deleted = request.POST.getlist('deleted')
        response['status'] = 'Select course(s) to delete!'
        for course_id in deleted:
            try:
                Course.objects.filter(id=course_id).delete()
                response['status'] = 'Course(s) deleted successfully'
            except:
                pass
    courses = Course.objects.all()
    response['courses'] = courses
    return render(request, 'story_5/delete.html', response)

templates/story_5/add.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Add Course{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Add Your Course</h1>
            <form method="POST" action="{% url 'add_course' %}">
                <table>
                    {% csrf_token %}
                    <tr><th><label for="id_course_name">Course Name:</label></th><td>{{ form.course_name }}</td></tr>
                    <tr><th><label for="id_lecturer">Lecturer:</label></th><td>{{ form.lecturer }}</td></tr>
                    <tr><th><label for="id_credits">Credits:</label></th><td>{{ form.credits }}</td></tr>
                    <tr><th><label for="id_description">Description:</label></th><td>{{ form.description }}</td></tr>
                    <tr><td><br></td></tr>
                    <tr><td><input type="submit" value="Add"></td></tr>
                </table>
            </form>
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
        {% if status %}
            <script>
                alert("{{ status }}")
            </script>
        {% endif %}
{% endblock %}

templates/story_5/delete.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Delete Course{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Delete Your Course(s)</h1>
            {% if courses %}
            <form method="POST" action="{% url 'delete_course' %}">
                {% csrf_token %}
                <table class="record-table" style="border: 1px solid black;">
                    <tr><td style="border: 1px solid black;"><strong>Select</strong></td><td style="border: 1px solid black;"><strong>Course Name</strong></td><td style="border: 1px solid black;"><strong>Lecturer</strong></td><td style="border: 1px solid black;"><strong>Credits</strong></td><td style="border: 1px solid black;"><strong>Description</strong></td></tr>
                    {% for course in courses %}
                    <tr><td style="border: 1px solid black;"><input type="checkbox" value="{{ course.id }}" name="deleted"></td><td style="border: 1px solid black;">{{ course.course_name }}</td><td style="border: 1px solid black;">{{ course.lecturer }}</td><td style="border: 1px solid black;">{{ course.credits }}</td><td style="border: 1px solid black;">{{ course.description }}</td></tr>
                    {% endfor %}
                </table>
                <input type="submit" onclick="return confirm('Are you sure to delete selected?')" value="Delete">
            </form>
            {% else %}
            <i>There are no course(s) recorded in the database.</i>
            {% endif %}
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
{% if status %}
    <script>
        alert("{{ status }}")
    </script>
{% endif %}
{% endblock %}