story_4/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('projects', views.projects, name='projects'),
    path('stories', views.stories, name='stories'),
    path('gallery', views.gallery, name='gallery'),
]

story_6/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.event, name='events'),
    path('add', views.addEvent, name='add_event'),
    path('delete', views.deleteEvent, name='delete_event'),
    path('<int:event_id>/register', views.addParticipant, name='add_participant'),
    path('delete-participants', views.deleteParticipant, name='delete_participant'),
]

story_ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='story_1/profil.html'))
    path('', include('story_4.urls')),
    path('courses/', include('story_5.urls')),
    path('events/', include('story_6.urls')),
    path('search/', include('story_8.urls')),
    path('accounts/', include('story_9.urls')),
]

story_6/models.py
from django.db import models
from django.utils.timezone import now

class Event(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField(default=now)
    place = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
class Participant(models.Model):
    name = models.CharField(max_length=200)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    def __str__(self):
        return self.name + ' - ' + str(self.event)

story_6/forms.py
from django import forms
from .models import *

class AddEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'date', 'place', 'description']
    
    name = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'autocomplete':'off'}))
    date = forms.DateField(required=True)
    place = forms.CharField(max_length=200, required = True, widget=forms.TextInput(attrs={'autocomplete':'off'}))
    description = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'autocomplete':'off'}))
    
class AddParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ['name']
        exclude = ['event']
        
    name = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'autocomplete':'off'}))

story_6/views.py
from django.shortcuts import render
from .forms import *
from .models import *

def event(request):
    events = Event.objects.all()
    events_with_participants_list = []
    for event in events:
        participants = Participant.objects.filter(event=event)
        events_with_participants_list.append([event, participants])
    if (len(events_with_participants_list) > 0):
        response = {'events' : events_with_participants_list}
    else:
        response = {}
    return render(request, 'story_6/events.html', response)

def addEvent(request):
    response = {'form' : AddEventForm}
    if (request.method == 'POST'):
        form = AddEventForm(request.POST)
        if (form.is_valid()):
            form.save()
            response['status'] = 'Event added successfully'
    return render(request, 'story_6/add_event.html', response)
    
def addParticipant(request, event_id):
    response = {'form' : AddParticipantForm, 'event_id' : event_id}
    try:
        event_name = Event.objects.filter(id=event_id)[0]
    except:
        return render(request, 'story_6/add_participant.html')
    response['event_name'] = event_name
    if (request.method == 'POST'):
        form = AddParticipantForm(request.POST)
        if (form.is_valid()):
            participant = form.save(commit=False)
            participant.event = Event.objects.filter(id=event_id)[0]
            participant.save()
            response['status'] = 'Successfully registered to the event'
    return render(request, 'story_6/add_participant.html', response)

def deleteEvent(request):
    response = {}
    if (request.method == 'POST'):
        deleted = request.POST.getlist('deleted')
        response['status'] = 'Select event(s) to delete!'
        for event_id in deleted:
            Event.objects.filter(id=event_id).delete()
            response['status'] = 'Event(s) deleted successfully'
    events = Event.objects.all()
    response['events'] = events
    return render(request, 'story_6/delete_event.html', response)

def deleteParticipant(request):
    response = {}
    if (request.method == 'POST'):
        deleted = request.POST.getlist('deleted')
        response['status'] = 'Select participant(s) to delete!'
        for participant_id in deleted:
            Participant.objects.filter(id=participant_id).delete()
            response['status'] = 'Participant(s) deleted successfully'
    participants = Participant.objects.all()
    response['participants'] = participants
    return render(request, 'story_6/delete_participant.html', response)

templates/story_6/add_event.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Add event{% endblock %}
{% block style %}
        <!--Add your custom style here-->
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Add Event</h1>
            <form method="POST" action="{% url 'add_event' %}">
                <table>
                    {% csrf_token %}
                    <tr><th><label for="id_name">Name:</label></th><td>{{ form.name }}</td></tr>
                    <tr><th><label for="id_date">Date:</label></th><td><input type="date" id="date" name="date" value="" required></td></tr>
                    <tr><th><label for="id_place">Place:</label></th><td>{{ form.place }}</td></tr>
                    <tr><th><label for="id_description">Description:</label></th><td>{{ form.description }}</td></tr>
                    <tr><td><br></td></tr>
                    <tr><td><input type="submit" value="Add"></td></tr>
                </table>
            </form>
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
        {% if status %}
            <script>
                alert("{{ status }}")
            </script>
        {% endif %}
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}

templates/story_6/add_participant.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Register Event{% endblock %}
{% block style %}
        <!--Add your custom style here-->
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Register to The Event</h1>
            <p>Fill your name to register event: <strong>{{ event_name }}</strong></p>
            {% if form %}
            <form method="POST" action="{% url 'add_participant' event_id=event_id %}">
                <table>
                    {% csrf_token %}
                    <tr><th><label for="id_name">Name:</label></th><td>{{ form.name }}</td></tr>
                    <tr><td><br></td></tr>
                    <tr><td><input type="submit" value="Add"></td></tr>
                </table>
            </form>
            {% else %}
            <i>Event not found! Please register to another event.</i>
            {% endif %}
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
        {% if status %}
            <script>
                alert("{{ status }}")
            </script>
        {% endif %}
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}

templates/story_6/delete_event.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Delete Event{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Delete event(s)</h1>
            {% if events %}
            <form method="POST" action="{% url 'delete_event' %}">
                {% csrf_token %}
                <table class="record-table" style="border: 1px solid black;">
                    <tr><td style="border: 1px solid black;"><strong>Select</strong></td><td style="border: 1px solid black;"><strong>Event Name</strong></td><td style="border: 1px solid black;"><strong>Date</strong></td><td style="border: 1px solid black;"><strong>Place</strong></td><td style="border: 1px solid black;"><strong>Description</strong></td></tr>
                    {% for event in events %}
                    <tr><td style="border: 1px solid black;"><input type="checkbox" value="{{ event.id }}" name="deleted"></td><td style="border: 1px solid black;">{{ event.name }}</td><td style="border: 1px solid black;">{{ event.date }}</td><td style="border: 1px solid black;">{{ event.place }}</td><td style="border: 1px solid black;">{{ event.description }}</td></tr>
                    {% endfor %}
                </table>
                <input type="submit" onclick="return confirm('Are you sure to delete selected?')" value="Delete">
            </form>
            {% else %}
            <i>There are no event(s) recorded in the database.</i>
            {% endif %}
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
{% if status %}
    <script>
        alert("{{ status }}")
    </script>
{% endif %}
{% endblock %}

templates/story_6/delete_participant.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Delete Course{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Delete Participants(s)</h1>
            {% if participants %}
            <form method="POST" action="{% url 'delete_participant' %}">
                {% csrf_token %}
                <table class="record-table" style="border: 1px solid black;">
                    <tr><td style="border: 1px solid black;"><strong>Select</strong></td><td style="border: 1px solid black;"><strong>Participant Name</strong></td><td style="border: 1px solid black;"><strong>Event Name</strong></td></tr>
                    {% for participant in participants %}
                    <tr><td style="border: 1px solid black;"><input type="checkbox" value="{{ participant.id }}" name="deleted"></td><td style="border: 1px solid black;">{{ participant.name }}</td><td style="border: 1px solid black;">{{ participant.event }}</td></tr>
                    {% endfor %}
                </table>
                <input type="submit" onclick="return confirm('Are you sure to delete selected?')" value="Delete">
            </form>
            {% else %}
            <i>There are no participant(s) recorded in the database.</i>
            {% endif %}
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
{% if status %}
    <script>
        alert("{{ status }}")
    </script>
{% endif %}
{% endblock %}

templates/story_6/events.html
{% extends 'base.html' %}
{% block title %}Prajna Prasetya | Events{% endblock %}
{% block style %}
        <!--Add your custom style here-->
{% endblock %}
{% block content %}
        <div class="content">
            <h1>Events</h1>
            {% if events %}
            <!-- reference for css cards: https://www.youtube.com/watch?v=qJf8N46OEMk -->
            <div class="main-card">
                <section class="cards">
                    {% for event in events %}
                    <div class="card">
                        <div class="card__title text--medium">
                            <h4>{{ event.0.name }}</h4>
                        </div>
                        <div class="card__info">
                            <p class="text--medium">{{ event.0.description }}</p>
                            <p class="text--medium">Date: {{ event.0.date }}</p>
                            <p class="text--medium">Place: {{ event.0.place }}</p>
                            <p class="text--medium">Participants:</p>
                            <ul>
                                {% for participant in event.1 %}
                                <li><p class="text--medium">{{ participant.name }}</p></li>
                                {% empty %}
                                <li><p class="text--medium">No Participant yet</p></li>
                                {% endfor %}
                            </ul>
                            <button onclick="window.location.href = '{% url 'add_participant' event_id=event.0.id %}';">Register</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            <p><i>There are no event(s) right now.</i></p>
            {% endif %}
        </div>
        <div class="empty-div"><br><br><br><br><br><br><br><br></div>
{% endblock %}
{% block script %}
        <!-- add js here -->
{% endblock %}